spring:
  datasource:
    url: jdbc:mysql://localhost/order_mgmt
    username: root
    password: dudwl0804!
  thymeleaf:
    view-names: "views/*"
    prefix: "/WEB-INF/"
    suffix: ".html"

logging:
  level:
    org:
      springframework: ERROR

server:
  servlet:
    context-path: /kdt_spring_order_war_exploded