Spring :
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true  #ddl option
    hibernate:
      ddl-auto: create-drop
    database: H2
    open-in-view: false
    show-sql: true    #sql 쿼리 확인
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        query.in_clause_parameter_padding: true